tikos/__init__.py
from flask import Flask
from .extensions import views
from .extensions.db import mongo
from .functions import erro, login

def create_app(config_object="tikos.config.settings"):
    app = Flask(__name__)
    app.config["SECRET_KEY"] = "Secret"
    app.config.from_object(config_object)
    app.register_error_handler(404, erro.page_not_found)
    views.init_app(app)
    mongo.init_app(app)
    return app

tikos/extensions/views.py
from flask import Blueprint, render_template, request, redirect, session, url_for
from ..functions import products, financial, plates, login, config, logout, manage_pdf


bp = Blueprint(
                "bp", __name__,
                static_folder="static",
                template_folder="templates")


def init_app(app):
    app.register_blueprint(bp)


@bp.route("/", methods=["GET"])
def index():
    return login.verify_logged(products.list_products())


@bp.route("/login")
def loginAdm():
    if "login" not in session:
        return render_template("index.html")
    else:
        return redirect(url_for("bp.index"))


@bp.route('/auth', methods=["GET"])
def auth():
    return login.verify_logged(login.authLogin())


@bp.route("/product/new/", methods=["GET"])
def productView():
    return login.verify_logged(render_template("formProducts.html"))


@bp.route("/product/", methods=["POST", "GET"])
def product():
    return login.verify_logged(products.manageProduct())


@bp.route("/product/<name_product>/", methods=["GET", "PUT", "DELETE"])
def find_product(name_product):
    return login.verify_logged(products.specify_product(name_product.lower()))


@bp.route("/product/add_qntd/", methods=["POST"])
def add_qnt_produtcs():
    return login.verify_logged(products.add_product())


@bp.route("/product/withdraw_qntd/<name_product>/", methods=["PUT"])
def withdraw_qnt_produtcs(name_product):
    return login.verify_logged(products.withdraw_product(name_product.lower()))


@bp.route("/product/edit_qntd", methods=["POST"])
def edit_qnt_produtcs():
    return login.verify_logged(products.sent_new_qntd())


@bp.route("/pdf/")
def pdf():
    req = request.args
    return login.verify_logged(manage_pdf.select_pdf(req["tipo_pdf"]))

@bp.route("/financial/", methods=["GET"])
def view_financial():
    return login.verify_logged(financial.finance_graph())


@bp.route("/financial/new/", methods=["POST"])
def new_financial():
    return login.verify_logged(financial.new())


@bp.route("/plate/", methods=["POST", 'GET'])
def plate():
    return login.verify_logged(plates.managePlate())


@bp.route("/new_plate/")
def view_new_plate():
    return login.verify_logged(plates.list_form_plate())


@bp.route("/search_product", methods=["POST"])
def search_product():
    return login.verify_logged(products.search_product())


@bp.route("/plate/<name_plate>/", methods=["GET", "PUT", "DELETE"])
def find_plate(name_plate):
    return login.verify_logged(plates.specify_plate(name_plate.lower()))


@bp.route("/plate/edit_qntd", methods=["POST"])
def edit_qnt_plate():
    return login.verify_logged(plates.edit_plate())


@bp.route("/update/plate/<name_plate>", methods=["get"])
def updatePlate(name_plate):
    return login.verify_logged(plates.list_ingredients(name_plate))


@bp.route("/search_plate", methods=["POST"])
def search_plate():
    return login.verify_logged(plates.search_plate())


@bp.route("/delete_ingredient/<name_plate>/<ingredient_name>")
def delete_ingredient(name_plate, ingredient_name):
    return login.verify_logged(plates.remove_ingredient(name_plate, ingredient_name))


@bp.route("/reports/", methods=["GET"])
def view_reports():
    return login.verify_logged(financial.reports())


@bp.route("/logout/")
def logout_session():
    logout.logout_app()
    return login.verify_logged(redirect(url_for("bp.loginAdm")))


@bp.route("/config/", methods=["GET"])
def view_config():
     return login.verify_logged(config.list_configuration())


@bp.route("/default_config/", methods=["GET"])
def default_config():
    return login.verify_logged(config.default_configuration())


@bp.route("/new_user/", methods=["GET"])
def new_user():
    return login.verify_logged(config.create_user())


@bp.route("/delete_user/")
def delete_users():
    return login.verify_logged(config.delete_user())


@bp.route("/caixa/")
def view_cashier():
    return login.verify_logged(products.cashier())


@bp.route("/baixa/", methods=["POST"])
def abatimento():
    return login.verify_logged(plates.saida_de_prato())

tikos/templates/ResultPlate.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link href="https://fonts.googleapis.com/css2?family=Archivo&family=Poppins:wght@300&display=swap" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
    integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='css/plates.css') }}">
    <title>Pratos</title>
</head>
<body>
    <div>
        <header>
            <img src="{{ url_for('static', filename='images/ticos.png') }}" alt="Logo">
                <ul>
                    <a href="{{ url_for('bp.index') }}"><li><i class="fa fa-home"></i></li></a>
                    <a href="{{ url_for('bp.view_financial') }}"><li><i class="fa fa-money"></i></li></a>
                    <a href="{{ url_for('bp.view_reports' ) }}"><li><i class="fa fa-line-chart"></i></li></a>
                    <a href="{{ url_for('bp.plate') }}"><li><i class="fa fa-product-hunt"></i></li></a>
                    <a href="{{ url_for('bp.view_config') }}"><li><i class="fa fa-cogs"></i></li></a>
                    <a href="{{ url_for('bp.view_cashier') }}"><li><i class="fa fa-usd"></i></li></a>
                    <a href="{{ url_for('bp.logout_session') }}"><li><i class="fa fa-sign-out"></i></li></a>
                </ul>
        </header>
        <main>
            <h1 class="dashboard">Pratos</h1>
            <form action="{{ url_for('bp.search_plate') }}" method="POST">
                <label><input type="search" name="prato" list="pratos" placeholder="Buscar Prato"><button><i class="fa fa-search"></i></button></label>
                <datalist id="pratos">
                    {% for pt in listPlates2 %}
                    {% for name in pt %}
                        <option>{{ name.capitalize() }}</option>
                    {% endfor %}
                    {% endfor %}
                </datalist>
            </form>

            <span class="button">
                <a href="{{ url_for('bp.view_new_plate') }}" target="_self">
                    <button><i class="fa fa-plus"></i></button>
                </a>
            </span>

            <div class="items">
                {% for plate in listPlates1 %}
                    {% for item in plate %}
                        <div class="item">
                            <form class="submenu" method="post" action="/ideas/{{id}}?_method=DELETE">
                                <input type="hidden" name="_method" value="DELETE">
                                <div>
                                    <a href="/plate/{{ item }}/?_method=DELETE"><i class="fa fa-trash-o"></i></a>
                                    <a href="/update/plate/{{ item }}"><i class="fa fa-pencil"></i></a>
                                </div>
                                <p>{{ item.capitalize() }}</p>
                                <span><h3>R$ {{ plate[item]["preco_prato"] }}</h3></span>
                            </form>
                        </div>
                    {% endfor %}
                {% endfor %}
            </div>
        </main>
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
</body>
</html>

tikos/templates/ResultStock.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link href="https://fonts.googleapis.com/css2?family=Archivo&family=Poppins:wght@300&display=swap" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
    integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/home.css') }}">
    <title>Home</title>
</head>
<body>
    <div>
        <header>
            <img src="{{ url_for('static', filename='images/ticos.png') }}" alt="Logo">
                <ul>
                    <a href="{{ url_for('bp.index') }}"><li><i class="fa fa-home"></i></li></a>
                    <a href="{{ url_for('bp.view_financial') }}"><li><i class="fa fa-money"></i></li></a>
                    <a href="{{ url_for('bp.view_reports' ) }}"><li><i class="fa fa-line-chart"></i></li></a>
                    <a href="{{ url_for('bp.plate') }}"><li><i class="fa fa-product-hunt"></i></li></a>
                    <a href="{{ url_for('bp.view_config') }}"><li><i class="fa fa-cogs"></i></li></a>
                    <a href="{{ url_for('bp.view_cashier') }}"><li><i class="fa fa-usd"></i></li></a>
                    <a href="{{ url_for('bp.logout_session') }}"><li><i class="fa fa-sign-out"></i></li></a>
                </ul>
        </header>
        <main>
            <h1 class="dashboard">Estoque</h1>
            <form action="{{ url_for('bp.search_product') }}" method="POST">
                <label><input type="search" name="produto" list="produtos" placeholder="Buscar Produto"><button type="submit"><i class="fa fa-search"></i></button></label>
                <datalist id="produtos">
                    {% for pd in listProducts2 %}
                    {% for nm in pd %}
                        <option>{{ nm.capitalize() }}</option>
                    {% endfor %}
                    {% endfor %}
                </datalist>
            </form>

            <span class="button"><a href="{{ url_for('bp.productView') }}" target="_self"><button><i class="fa fa-plus" aria-hidden="true"></i></button></a></span>

            <div class="items">
                {% for product in listProducts %}
                {% for item in product %}
                    {% if product[item]["quantidade"] > product[item]["minimo"]+(product[item]["minimo"]*50)/100 %}
                        <div class="item">

                            <form class="submenu" method="post" action="/ideas/{{id}}?_method=DELETE">
                                <input type="hidden" name="_method" value="DELETE">
                                <div>
                                    <a href="/product/{{ item }}/?_method=DELETE"><i class="fa fa-trash-o"></i></a>
                                    <a><i class="fa fa-pencil"></i></a>
                                </div>
                            </form>

                            <form class="form-items" action="{{ url_for('bp.edit_qnt_produtcs') }}" method="POST">
                                <div class="inputs"><label class="label1"></label><input type="number" min="0" name="qntd" class="qntd" value="{{ product[item]['quantidade'] }}" required disabled></div>
                                <div class="inputs"><label class="label2"></label><input type="number" min="0" name='min' class="min" value="{{ product[item]['minimo'] }}" required disabled></div>
                                <input type="hidden" name='nm_product' value="{{ item }}">
                                <button type="submit" class="submit"><i class="fa fa-check"></i></button>
                                <div class="inputs"><label class="label3"></label><input type="text" name='new_name' class="product" value="{{ item.capitalize() }}" onkeypress="return Letras(event,this);" required disabled></div>
                                <div class="inputs"><label class="label4"></label><input type="text" name='unidade' class="unity" value="{{ product[item]['unidade'] }}" required disabled></div>
                            </form>

                            <button class="times"><i class="fa fa-times"></i></button>

                            <form class="submenu" method="post" action="/ideas/{{id}}?_method=PUT">
                                <input type="hidden" name="_method" value="PUT">
                            </form>

                        </div>
                    {% elif product[item]["quantidade"] <= product[item]["minimo"] + (product[item]["minimo"]*50)/100 and product[item]["quantidade"] > product[item]["minimo"] %}
                        <div class="item" style="background-color: #FFD700;">
                            <form class="submenu" method="post" action="/ideas/{{id}}?_method=DELETE">
                                <input type="hidden" name="_method" value="DELETE">
                                <div>
                                    <a href="/product/{{ item }}/?_method=DELETE"><i class="fa fa-trash-o"></i></a>
                                    <a ><i class="fa fa-pencil"></i></a>
                                </div>
                            </form>

                            <form class="form-items"action="{{ url_for('bp.edit_qnt_produtcs') }}" method="POST">
                                <div class="inputs"><label class="label1"></label><input type="number" min="0" name="qntd" class="qntd" value="{{ product[item]['quantidade'] }}" required disabled></div>
                                <div class="inputs"><label class="label2"></label><input type="number" min="0" name='min' class="min" value="{{ product[item]['minimo'] }}" required disabled></div>
                                <input type="hidden" name='nm_product' value="{{ item }}">
                                <button type="submit" class="submit"><i class="fa fa-check"></i></button>
                                <div class="inputs"><label class="label3"></label><input type="text" name='new_name' class="product" value="{{ item.capitalize() }}" onkeypress="return Letras(event,this);" required disabled></div>
                                <div class="inputs"><label class="label4"></label><input type="text" name='unidade' class="unity" value="{{ product[item]['unidade'] }}" required disabled></div>
                            </form>

                            <button class="times"><i class="fa fa-times"></i></button>

                            <form class="submenu" method="post" action="/ideas/{{id}}?_method=PUT">
                                <input type="hidden" name="_method" value="PUT">
                            </form>
                        </div>
                    {% elif product[item]["quantidade"] <= product[item]["minimo"] %}
                        <div class="item" style="background-color: #B22222;">
                            <form class="submenu" method="post" action="/ideas/{{id}}?_method=DELETE">
                                <input type="hidden" name="_method" value="DELETE">
                                <div>
                                    <a href="/product/{{ item }}/?_method=DELETE"><i class="fa fa-trash-o"></i></a>
                                    <a ><i class="fa fa-pencil"></i></a>
                                </div>
                            </form>

                            <form class="form-items" action="{{ url_for('bp.edit_qnt_produtcs') }}" method="POST">
                                <div class="inputs"><label class="label1"></label><input type="number" min="0" name="qntd" class="qntd" value="{{ product[item]['quantidade'] }}" required disabled></div>
                                <div class="inputs"><label class="label2"></label><input type="number" min="0" name='min' class="min" value="{{ product[item]['minimo'] }}" required disabled></div>
                                <input type="hidden" name='nm_product' value="{{ item }}">
                                <button type="submit" class="submit"><i class="fa fa-check"></i></button>
                                <div class="inputs"><label class="label3"></label><input type="text" name='new_name' class="product" value="{{ item.capitalize() }}" onkeypress="return Letras(event,this);" required disabled></label></div>
                                <div class="inputs"><label class="label4"></label><input type="text" name='unidade' class="unity" value="{{ product[item]['unidade'] }}" required disabled></div>
                            </form>

                            <button class="times"><i class="fa fa-times"></i></button>

                            <form class="submenu" method="post" action="/ideas/{{id}}?_method=PUT">
                                <input type="hidden" name="_method" value="PUT">
                            </form>
                        </div>
                    {% endif %}
                {% endfor %}
                {% endfor %}
            </div>
        </main>
    </div>
    <script src="{{ url_for('static', filename='js/stock.js') }}"></script>
</body>
</html>

tikos/templates/Stock.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link href="https://fonts.googleapis.com/css2?family=Archivo&family=Poppins:wght@300&display=swap" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
    integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/home.css') }}">
    <title>Home</title>
</head>
<body>
    <div>
        <header>
            <img src="{{ url_for('static', filename='images/ticos.png') }}" alt="Logo">
                <ul>
                    <a href="{{ url_for('bp.index') }}"><li><i class="fa fa-home"></i></li></a>
                    <a href="{{ url_for('bp.view_financial') }}"><li><i class="fa fa-money"></i></li></a>
                    <a href="{{ url_for('bp.view_reports' ) }}"><li><i class="fa fa-line-chart"></i></li></a>
                    <a href="{{ url_for('bp.plate') }}"><li><i class="fa fa-product-hunt"></i></li></a>
                    <a href="{{ url_for('bp.view_config') }}"><li><i class="fa fa-cogs"></i></li></a>
                    <a href="{{ url_for('bp.view_cashier') }}"><li><i class="fa fa-usd"></i></li></a>
                    <a href="{{ url_for('bp.logout_session') }}"><li><i class="fa fa-sign-out"></i></li></a>
                </ul>
        </header>
        <main>
            <h1 class="dashboard">Estoque</h1>
            <form action="{{ url_for('bp.search_product') }}" method="POST">
                <label><input type="search" name="produto" list="produtos" placeholder="Buscar Produto"><button type="submit"><i class="fa fa-search"></i></button></label>
                <datalist id="produtos">
                    {% for pd in listProducts %}
                    {% for nm in pd %}
                        <option>{{ nm.capitalize() }}</option>
                    {% endfor %}
                    {% endfor %}
                </datalist>
            </form>

            <span class="button"><a href="{{ url_for('bp.productView') }}" target="_self"><button><i class="fa fa-plus" aria-hidden="true"></i></button></a></span>
            
            {% for message in get_flashed_messages(with_categories=true) %}
                {% if message[0] == "erro" %}
                    <div class="message">Erro: <span> {{ message[1] }} </span></div>
                {% else %}
                    <div class="message2">Sucesso: <span> {{ message[1] }}</span></div>
                {% endif %}
            {% endfor %}

            <div class="items">
                {% for product in listProducts %}
                {% for item in product %}
                    {% if product[item]["quantidade"] > product[item]["minimo"]+(product[item]["minimo"]*50)/100 %}
                        <div class="item">

                            <form class="submenu" method="post" action="/ideas/{{id}}?_method=DELETE">
                                <input type="hidden" name="_method" value="DELETE">
                                <div>
                                    <a href="/product/{{ item }}/?_method=DELETE"><i class="fa fa-trash-o"></i></a>
                                    <a><i class="fa fa-pencil"></i></a>
                                </div>
                            </form>

                            <form class="form-items" action="{{ url_for('bp.edit_qnt_produtcs') }}" method="POST">
                                <div class="inputs"><label class="label1"></label><input type="number" min="0" name="qntd" class="qntd" value="{{ product[item]['quantidade'] }}" required disabled></div>
                                <div class="inputs"><label class="label2"></label><input type="number" min="0" name='min' class="min" value="{{ product[item]['minimo'] }}" required disabled></div>
                                <input type="hidden" name='nm_product' value="{{ item }}">
                                <button type="submit" class="submit"><i class="fa fa-check"></i></button>
                                <div class="inputs"><label class="label3"></label><input type="text" name='new_name' class="product" value="{{ item.capitalize() }}" onkeypress="return Letras(event,this);" required disabled></div>
                                <div class="inputs"><label class="label4"></label><input type="text" name='unidade' class="unity" value="{{ product[item]['unidade'] }}" required disabled></div>
                            </form>

                            <button class="times"><a href="{{ url_for('bp.index') }}"><i class="fa fa-times"></i></a></button>

                            <form class="submenu" method="post" action="/ideas/{{id}}?_method=PUT">
                                <input type="hidden" name="_method" value="PUT">
                            </form>

                        </div>
                    {% elif product[item]["quantidade"] <= product[item]["minimo"] + (product[item]["minimo"]*50)/100 and product[item]["quantidade"] > product[item]["minimo"] %}
                        <div class="item" style="background-color: #FFD700;">
                            <form class="submenu" method="post" action="/ideas/{{id}}?_method=DELETE">
                                <input type="hidden" name="_method" value="DELETE">
                                <div>
                                    <a href="/product/{{ item }}/?_method=DELETE"><i class="fa fa-trash-o"></i></a>
                                    <a><i class="fa fa-pencil"></i></a>
                                </div>
                            </form>

                            <form class="form-items"action="{{ url_for('bp.edit_qnt_produtcs') }}" method="POST">
                                <div class="inputs"><label class="label1"></label><input type="number" min="0" name="qntd" class="qntd" value="{{ product[item]['quantidade'] }}" required disabled></div>
                                <div class="inputs"><label class="label2"></label><input type="number" min="0" name='min' class="min" value="{{ product[item]['minimo'] }}" required disabled></div>
                                <input type="hidden" name='nm_product' value="{{ item }}">
                                <button type="submit" class="submit"><i class="fa fa-check"></i></button>
                                <div class="inputs"><label class="label3"></label><input type="text" name='new_name' class="product" value="{{ item.capitalize() }}" onkeypress="return Letras(event,this);" required disabled></div>
                                <div class="inputs"><label class="label4"></label><input type="text" name='unidade' class="unity" value="{{ product[item]['unidade'] }}" required disabled></div>
                            </form>

                            <button class="times"><a href="{{ url_for('bp.index') }}"><i class="fa fa-times"></a></i></button>

                            <form class="submenu" method="post" action="/ideas/{{id}}?_method=PUT">
                                <input type="hidden" name="_method" value="PUT">
                            </form>
                        </div>
                    {% elif product[item]["quantidade"] <= product[item]["minimo"] %}
                        <div class="item" style="background-color: #B22222;">
                            <form class="submenu" method="post" action="/ideas/{{id}}?_method=DELETE">
                                <input type="hidden" name="_method" value="DELETE">
                                <div>
                                    <a href="/product/{{ item }}/?_method=DELETE"><i class="fa fa-trash-o"></i></a>
                                    <a><i class="fa fa-pencil"></i></a>
                                </div>
                            </form>

                            <form class="form-items" action="{{ url_for('bp.edit_qnt_produtcs') }}" method="POST">
                                <div class="inputs"><label class="label1"></label><input type="number" min="0" name="qntd" class="qntd" value="{{ product[item]['quantidade'] }}" required disabled></div>
                                <div class="inputs"><label class="label2"></label><input type="number" min="0" name='min' class="min" value="{{ product[item]['minimo'] }}" required disabled></div>
                                <input type="hidden" name='nm_product' value="{{ item }}">
                                <button type="submit" class="submit"><i class="fa fa-check"></i></button>
                                <div class="inputs"><label class="label3"></label><input type="text" name='new_name' class="product" value="{{ item.capitalize() }}" onkeypress="return Letras(event,this);" required disabled></label></div>
                                <div class="inputs"><label class="label4"></label><input type="text" name='unidade' class="unity" value="{{ product[item]['unidade'] }}" required disabled></div>
                            </form>

                            <button class="times"><a href="{{ url_for('bp.index') }}"><i class="fa fa-times"></i></a></button>

                            <form class="submenu" method="post" action="/ideas/{{id}}?_method=PUT">
                                <input type="hidden" name="_method" value="PUT">
                            </form>
                        </div>
                    {% endif %}
                {% endfor %}
                {% endfor %}
            </div>
        </main>
    </div>
    <script src="{{ url_for('static', filename='js/stock.js') }}"></script>
</body>
</html>

tikos/templates/caixa.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link href="https://fonts.googleapis.com/css2?family=Archivo&family=Poppins:wght@300&display=swap" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
    integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/caixa.css') }}">
    <title>Caixa</title>
</head>
<body>
    <div>
        <header>
            <img src="{{ url_for('static', filename='images/ticos.png') }}" alt="Logo">
                <ul>
                    <a href="{{ url_for('bp.index') }}"><li><i class="fa fa-home"></i></li></a>
                    <a href="{{ url_for('bp.view_financial') }}"><li><i class="fa fa-money"></i></li></a>
                    <a href="{{ url_for('bp.view_reports' ) }}"><li><i class="fa fa-line-chart"></i></li></a>
                    <a href="{{ url_for('bp.plate') }}"><li><i class="fa fa-product-hunt"></i></li></a>
                    <a href="{{ url_for('bp.view_config') }}"><li><i class="fa fa-cogs"></i></li></a>
                    <a href="{{ url_for('bp.view_cashier') }}"><li><i class="fa fa-usd"></i></li></a>
                    <a href="{{ url_for('bp.logout_session') }}"><li><i class="fa fa-sign-out"></i></li></a>
                </ul>
        </header>
        <main>
            <h1>Caixa</h1>
            <div class="tab">
                <input class="aba" type="radio" name="tabs" id="tab1" checked>
                <label for="tab1">Registrar Vendas</label>

                <input class="aba" type="radio" name="tabs" id="tab2">
                <label for="tab2">Reposição de Estoque</label>

                <input class="aba" type="radio" name="tabs" id="tab3">
                <label for="tab3">Nome da nova tela</label>
                <div class="tabs">
                    <div class="content">
                        <form action="{{ url_for('bp.abatimento') }}" method="post">
                            <div class="conteudo">
                                <select class="campos margemCamposTop" name="prato" required>
                                    {% for prato in list_plate %}
                                        <option>{{ prato.capitalize() }}</option>
                                    {% endfor %}
                                </select>
                                <input class="campos" type="number" min="0" name="quantidade" placeholder="Quantidade vendida:" required>
                                <button class="btn-registrar">Registrar</button>
                            </div>
                        </form>
                    </div>
                    <div class="content">
                        <div class="conteudo">
                            <form action="{{ url_for('bp.add_qnt_produtcs') }}" method="POST">
                                <select class="campos margemCamposTop" name="produto" type="text" placeholder="Produto:" required>
                                    {% for produto in list_products %}
                                        <option>{{ produto.capitalize() }}</option>
                                    {% endfor %}
                                </select>
                                <input class="campos" name="quantidade" min="0" type="number" placeholder="Quantidade comprada:" required>
                                <button class="btn-registrar" type="submit">Registrar</button>
                            </form>
                        </div>
                    </div>
                    <div class="content">
                        <div class="conteudo">
                            <form action="" method="post">
                                <h1>Esperar o vitor mandar essa parte</h1>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</body>
</html>

tikos/templates/notfound.html
{% extends 'base.html' %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/notFound.css') }}">
    <title>404 - Not Found</title>
{% endblock %}

{% block content %}
    <img class="logo" src="{{ url_for('static', filename='images/pp-preview.png') }}" >
    <p> ERRO 404! </p>
    <p> A pagina que você tentou acessar não existe!</p>
    <a href="{{ url_for('bp.index') }}"> Voltar ao inicio </a>
{% endblock %}